### ISSUE TITLE
Installing the UVC driver problem with 05-15 Yocto Image

### ISSUE THREAD

**Issue by r3n33** [drejkim/edi-cam#1]
Yesterday I loaded the latest Yocto image from Intel and proceeded to follow the edi-cam instructions. In doing so I noticed performing opkg install kernel-module-uvcvideo will break the now included uvcvideo. This step is no longer needed with the latest Yocto build.

**Comment by estherjk** [comment]
@r3n33 thanks for this. I've updated the README to reflect this.

**Comment by jamesleo** [comment]
But I can't find /dev/video0, why?
the VID=1C4F,PID=3000
