### ISSUE TITLE
server not implemented

### ISSUE THREAD

**Issue by mrcrocodile556** [drejkim/edi-cam#13]
My webcam is  Logitech C270 however when i node server.js it only display

  WebSocket server listening on port 8084
  HTTP server listening on port 8080
  Listening for video stream on port 8082 

According to your documentation, there is a missing line of 
"Stream Connected: 127.0.0.1:52995 size: 320x240"

Also, when i run my web server of http://172.27.152.201:8084 , only a white screen with words "not implemented" is displayed.

Can you suggest where did i go wrong?

Cheers!

**Comment by estherjk** [comment]
Hi, a couple things:
- Can you open the developer console in your web browser? Are there any messages shown?
- Can you double-check that `wsUrl` has been updated `web/client/index.html` per the instructions?

**Comment by mrcrocodile556** [comment]
The developer console seems to be blank.

My wsUrl is as followed:
var wsUrl = 'ws://172.27.152.201.local:8084/';

However when i navigate to my server, I am using http://172.27.152.201.local:8084/

Do i have to change my wsUrl to http:// instead ?

**Comment by estherjk** [comment]
Can you try `ws://172.27.152.201:8084` instead? You typically need to write `local` after the network name of your Edison, but not with the IP address. Let me know if that resolves your problem!

**Comment by mrcrocodile556** [comment]
Hi, I tried replacing 8084 with 8080 and I am able to run my server with http://172.27.152.201:8080/ 

However, now it only shows "Loading"

Any idea where did i went wrong this time?

**Comment by estherjk** [comment]
Can you use 8084 instead of 8080? The WebSocket server is listening on port 8084.

**Comment by mrcrocodile556** [comment]
My wsUrl in index.html is currently saved as:
 var wsUrl = 'http://172.27.152.201:8084/';

However i can only run the server using  172.27.152:8080 and not 8084.

**Comment by estherjk** [comment]
Hmm, not sure if I fully understand the issue you're experiencing. Can you explain in more detail what's going on?

**Comment by mrcrocodile556** [comment]
My apology for not detailed explanation. I'm new to programming :)

There are a few issues I'm currently facing.

Web server told me it was "not implemented" when i tried with ws://172.27.152.201:8084 and http://172.27.152.201:8084 however I'm able to run only with http://172.27.251.201:8080 with only the "loading" word without any live footage of my webcam which you told me were wrong. 

Is there a difference between navigating with ws:// and http://?

For installation of ffmpeg, I only wget http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz into my bin folder and did not change anything. Did i execute this step correctly?

According to your guide, After node server.js there should be four lines being output, however I'm missing the last line of 
"Stream Connected: 127.0.0.1:52995 size: 320x240"

Cheers!

**Comment by estherjk** [comment]
Thanks for providing more details!

Can you try installing ffmpeg with the shell script (`bin/install_ffmpeg.sh`) I provide? Please see the instructions on installing ffmpeg. The reason why is that I download the 32-bit version of ffmpeg, unpack it, and move it to another directory that the code is expecting. This might actually be the source of the issues you're experiencing.

Also, `ws://` is used for the WebSocket server instead of `http://`as its URI scheme. So, try using `ws://` instead of `'http://`.

**Comment by mrcrocodile556** [comment]
Do you mean i have to vi install_ffmpeg.sh and then replace this line:
FNAME=ffmpeg-release-32bit-static.tar.xz ? 

Do i replace it with the 64bit 3.0.1 release version or the 64bit that is built on 20160409 ?

According to http://www.instructables.com/id/Intel-Edison-IP-Webcam/?ALLSTEPS , 

i will just replace it with: 
FNAME=ffmpeg-2.5.1-32bit-static.tar.xz

Am i doing it right?

**Comment by estherjk** [comment]
You should be able to run `install_ffmpeg.sh` without making any modifications. Can you try that?

**Comment by mrcrocodile556** [comment]
What do you mean by run "install_ffmpeg.sh".

My apology, I'm a beginner and don't quite understand. What commands do i have to run?

Also, i discover another issue, when i run lsmod I'm able to find my uvc driver however there isnt any light appearing on my Logitech C270 webcam. Is this normal? Am i suppose to see lights on my camera yet if it is already connected ?

**Comment by estherjk** [comment]
Can you try running the commands below? Also, please see the comments above each command.

``` bash
# If necessary, please change this to wherever edi-cam is located on your Edison
cd ~/edi-cam/bin

# Run install_ffmpeg.sh
./install_ffmpeg.sh
```

It should be okay if the webcam light isn't appearing. It should turn on when the server runs successfully without errors.

**Comment by mrcrocodile556** [comment]
This is the output when i run the command of ./install_ffmpeg.sh

Creating ~/bin directory if it doesn't exist...
Removing old versions of ffmpeg...
Downloading ffmpeg...
--2016-04-11 23:00:09--  http://johnvansickle.com/ffmpeg/releases/ffmpeg-2.4.3-32bit-static.tar.xz
Resolving johnvansickle.com... 199.79.62.21
Connecting to johnvansickle.com|199.79.62.21|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-04-11 23:00:10 ERROR 404: Not Found.

Unpacking...
tar: can't open '/home/root/bin/ffmpeg-2.4.3-32bit-static.tar.xz': No such file or directory
Cleaning up...
rm: can't remove '/home/root/bin/ffmpeg-2.4.3-32bit-static.tar.xz': No such file or directory
mv: can't rename '/home/root/bin/ffmpeg*/': No such file or directory

**Comment by estherjk** [comment]
When running `./install_ffmpeg.sh`, did you use the original version of the script? It should run just fine... at least when I tried this morning.

When you open `install_ffmpeg.sh`, can you double-check that `FNAME` is the same as my original version, i.e. `FNAME=ffmpeg-release-32bit-static.tar.xz`?

**Comment by mrcrocodile556** [comment]
I think i accidentally edited it before, but now  that i've change back to the original version im able to unpack it. 

Now, that I'm done unpacking, does this mean I'm ready to view my webcam?

**Comment by estherjk** [comment]
Okay, great! Can you please try re-running the web server? Hopefully, it'll work now.

**Comment by mrcrocodile556** [comment]
It's working perfectly now! Thank you so much Esther :) 

Also, if i want to adjust the resolution i would just need to edit the following numbers right?  
<canvas id="canvas-video" width="640" height="480">

**Comment by estherjk** [comment]
Glad it's working for you now!

Please see https://github.com/drejkim/edi-cam/issues/6 if you want to adjust the resolution
