### ISSUE TITLE
Setting up ON and OFF button

### ISSUE THREAD

**Issue by mrcrocodile556** [drejkim/edi-cam#14]
Hi, 

May i know if it is possible to create a ON and OFF button on the webpage?
If it is, any guide that i can follow through? 

Cheers!

**Comment by estherjk** [comment]
You can try adding ON / OFF buttons to the webpage and using JavaScript to play, pause, or stop the video. If you look at [jsmpg.js](https://github.com/drejkim/edi-cam/blob/master/web/client/jsmpg.js), there are play(), pause(), and stop() functions for the client-side streamer. Take a look at the functions and see if they're able to work for you.

**Comment by mrcrocodile556** [comment]
Is there any steps i can follow through online?

Unfortunately, I do not know Javascripting.

**Comment by estherjk** [comment]
Not sure if there will be a step-by-step guide available for this specific application. I do suggest you look through some HTML, CSS, and JavaScript tutorials, like [Codecademy - HTML & CSS](https://www.codecademy.com/learn/web) and [Codecademy - JavaScript](https://www.codecademy.com/learn/javascript). I think this will be very helpful in the long term.

**Comment by mrcrocodile556** [comment]
Thank you for the useful links.

Do you know roughly which part of the codes or which line am i suppose to modify?

**Comment by mrcrocodile556** [comment]
Thank you for the useful links!
