### ISSUE TITLE
Motion detecting function

### ISSUE THREAD

**Issue by mrcrocodile556** [drejkim/edi-cam#16]
Hello, 
I have been trying to modify a motion detecing function on your project.

I have found a similar [link](http://www.instructables.com/id/Edison-monitoring-system-with-motion-detection-and/?ALLSTEPS) regarding this function however I am unable to do so.

Do you have any guide i am able to follow regarding motion?

Cheers!

**Comment by estherjk** [comment]
I have seen this link before for using the motion package. If you're having issues, I'd definitely reach out to the author of the instructable!
