### ISSUE TITLE
Streaming on Mobile

### ISSUE THREAD

**Issue by just4give** [drejkim/edi-cam#19]
First of all, thanks a lot for this project. I followed the instruction and was able to stream video on browser. This works within same network. How can I make my edison streaming accessible from outside my home network? I want to make a mobile app and stream on the app. Any idea?

**Comment by estherjk** [comment]
Can you take a look at this discussion thread on my [website](http://drejkim.com/blog/2014/12/08/video-streaming-on-edison/#comment-2532184391)? Essentially, you'll need to add port forwarding to your router for both the site URL and the WebSocket URL (`wsUrl`). For more info on how to port forward, check out this [link](https://managewp.com/how-to-access-a-local-website-from-internet-with-port-forwarding). Hope this helps!

**Comment by just4give** [comment]
@drejkim thanks for your response. I used ngrok to do the port forwarding and now I can see the video stream on Ionic hybrid app.  Streaming on mobile is pretty slow and stops after few seconds. But that's a different issue I need to look at :)
