### ISSUE TITLE
edi-cam on galileo

### ISSUE THREAD

**Issue by xiochanik** [drejkim/edi-cam#2]
Hi, 
I have been trying to use your code with the Galileo board. Is there something I should be aware of within the code that's specific to Edison?? I changed to the appropriate repository for opkg and made sure my webcam is compatible with uvc. 
When I run server.js everything seems fine, but when I connect to the http server through my pc browser the loading notice shows shortly, and then nothing just a white image. There's no error with the web sockets nor the firewall. Also the led indicator in my webcam only stays on for 1 second or less then it shuts down. 
Thanks for your help

**Comment by estherjk** [comment]
@xiochanik can you provide the console output from node.js, as well as from the browser? I just want to see what's exactly outputted. Thanks!

**Comment by xiochanik** [comment]
This is what I get every time I run the code. 
![screenshot](https://cloud.githubusercontent.com/assets/11178851/6360391/3c12b02e-bc3f-11e4-8bab-fb635b46d381.jpg)

**Comment by estherjk** [comment]
@xiochanik It certainly looks like the server is running okay. However, I wonder if Galileo has enough power.... Can you try lowering the bitrate in `edi-cam/bin/do_ffmpeg.sh` using the `-b` flag? Right now it's set to 800k. I suggest starting low... for example 64k and see if the stream is visible.

**Comment by xiochanik** [comment]
I set the bitrate to 64k with 1 fps and nothing happen, then I try with 128 bitrate and 1 fps. Still nothing, the camera keeps going off, I do think the galileo lacks the power but I was hoping to make it work. 

Thanks for your help!
