### ISSUE TITLE
i want to send a message from client to server ? how can i ?

### ISSUE THREAD

**Issue by digerati73** [drejkim/edi-cam#3]
i want to send a message from index.html to server in edi-cam project

i make a button in index.html 
if user push a button and then some message is sended to server
and as message server do something

so i think, 
1. fix index.html
1. fix server.js , fix routs.js

? how can user send client's  custom message to server?

is this right?

**Comment by estherjk** [comment]
@digerati73 just for some background, the server-side uses the [ws](http://einaros.github.io/ws/) package to implement the WebSocket server. Take a look at their documentation to see how it's used. Meanwhile, the client-side just uses the [WebSocket API](https://developer.mozilla.org/en-US/docs/WebSockets/Writing_WebSocket_client_applications).

For illustration purposes, let's create a second WebSocket server, so we can leave the WebSocket server handling the video stream alone for now.

Here's an example of sending a simple message from the client to the server...

Add the following to `server.js`:

```
// Second WebSocket server on port 8086
var wsServer2 = new (ws.Server)({ port: 8086 });
wsServer2.on('connection', function(socket) {
  console.log('New WebSocket Connection on 2nd WebSocket server (' + wsServer2.clients.length + ' total)');

  socket.on('message', function(message) {
    console.log('received: %s', message);
  });

  socket.on('close', function(code, message) {
    console.log('Disconnected WebSocket on 2nd WebSocket server (' + wsServer2.clients.length + ' total)');
  });
});
```

Add the following to `index.html`:

```
// Second WebSocket client
var client2 = new WebSocket('ws://eejun-edison02.local:8086');
client2.onopen = function (event) {
  client2.send("Hello, server!");
};
```

When you run `node server.js` and launch the browser, you should see `Hello, server!` print on the console.

Feel free to modify in order to get this working with your button. Hopefully, it's pretty straightforward.

**Comment by digerati73** [comment]
thank you alot, code you suggest is so similar to my code especially server.js  and index.html, but i failed... so i am afraid of failing again... when i use 2nd websocket  , video stream is not received..at smartphone... but something is different. so i try again,

thank you again angel ^^

**Comment by digerati73** [comment]
root@edison:/etc/opkg/edi-cam/web/server# node server.js
MRAA Version : v0.5.2
WebSocket server listening on port 8084
HTTP server listening on port 8080
Listening for video stream on port 8082
Stream Connected: 127.0.0.1:48794 size: 320x240
New WebSocket Connection (1 total)
New Socket Connection on 2nd WebSocket server (1 total)
GET /favicon.ico 200 32.183 ms - 2132
Segmentation fault

what is Segmentation fault??

**Comment by digerati73** [comment]
********** index.html**************

    // Start the player
    var client = new WebSocket(wsUrl);
    var client2 = new WebSocket('ws://192.168.219.130:8086'); //wsUrl2);

   client2.onopen = function(event) {
    client2.send("fire");
   };

    var player = new jsmpeg(client, { canvas:canvas });
    // send custom message to server. LDH MADE
//     var button = document.getElementById('button');
//     button.onclick = function() {
//     client2.send("fire");
//     };

//    document.getElementById('button').onClick = function() {
    
//    if(client2.readyState === WebSocket.OPEN) {
//        client2.send("fire");
//    };

 </script>
   <h2> Control Page </h2>
   <hr />

   <form > //method="post">
   <input type="button" value="fire" name="name_fire"> <br />
          <br />
   </form>
</body>

************server.js******************

var wsServer2 = new (ws.Server)({ port: 8086 });
 wsServer2.on('connection', function(socket) {
  console.log('New Socket Connection on 2nd WebSocket server (' +
 wsServer2.clients.length+ ' total)');

  socket.on('fire',function(message) {
  console.log('received:'); // %s',message);
  });

  socket.on('fire222',function(message) {
  console.log('received: %s',message);
  });

  socket.on('close', function(code, message) {
  console.log('Disconnected Websocket on 2nd Websocket Server (' +
wsServer2.clients.length + ' total');
  });
});

// wsServer2.on('connection',function(socket) {
//console.log('New WebSocket 2 Connection (' +wsServer2.clients.length +
//' total)');

//  socket.on('fire', function() {
//  console.log('fire message is received');
//  });
//  socket.on('close', function(code, message) {
//  console.log('Disconnected webSocket (' + wsServer2.clients.length +
// 'total)');
//  });

// });

**Comment by digerati73** [comment]
i can't send a button clicked message to server ?  i make a function sendMsg() , but it is not called...
i can't understand.... websocket server 2 is connected by server  but, clicked message is not sended...
i check it browser debugger break point...but never breaked... at function in script...

![new index](https://cloud.githubusercontent.com/assets/7827525/6368083/ab5c7c66-bd1c-11e4-9610-0061be99b3f1.png)

**Comment by digerati73** [comment]
below is server.js. there is a code related with upper code 

![new serverjs](https://cloud.githubusercontent.com/assets/7827525/6368091/b8dbfb8c-bd1c-11e4-9c64-4d4faa881d60.png)

**Comment by digerati73** [comment]
before client connected
![in first](https://cloud.githubusercontent.com/assets/7827525/6368140/3ceed1c4-bd1d-11e4-81b9-1757bdb1eea4.png)

after client connected
![in second](https://cloud.githubusercontent.com/assets/7827525/6368143/41901d32-bd1d-11e4-9911-e3521af4d9f4.png)

**Comment by estherjk** [comment]
@digerati73 here's my full code:

`server.js`:

```
// modules
var childProcess = require('child_process')
  , express = require('express')
  , http = require('http')
  , morgan = require('morgan')
  , ws = require('ws');

// configuration files
var configServer = require('./lib/config/server');

// app parameters
var app = express();
app.set('port', configServer.httpPort);
app.use(express.static(configServer.staticFolder));
app.use(morgan('dev'));

// serve index
require('./lib/routes').serveIndex(app, configServer.staticFolder);

// HTTP server
http.createServer(app).listen(app.get('port'), function () {
  console.log('HTTP server listening on port ' + app.get('port'));
});

/// Video streaming section
// Reference: https://github.com/phoboslab/jsmpeg/blob/master/stream-server.js

var STREAM_MAGIC_BYTES = 'jsmp'; // Must be 4 bytes
var width = 320;
var height = 240;

// WebSocket server
var wsServer = new (ws.Server)({ port: configServer.wsPort });
console.log('WebSocket server listening on port ' + configServer.wsPort);

wsServer.on('connection', function(socket) {
  // Send magic bytes and video size to the newly connected socket
  // struct { char magic[4]; unsigned short width, height;}
  var streamHeader = new Buffer(8);

  streamHeader.write(STREAM_MAGIC_BYTES);
  streamHeader.writeUInt16BE(width, 4);
  streamHeader.writeUInt16BE(height, 6);
  socket.send(streamHeader, { binary: true });

  console.log('New WebSocket Connection (' + wsServer.clients.length + ' total)');

  socket.on('close', function(code, message){
    console.log('Disconnected WebSocket (' + wsServer.clients.length + ' total)');
  });
});

wsServer.broadcast = function(data, opts) {
  for(var i in this.clients) {
    if(this.clients[i].readyState == 1) {
      this.clients[i].send(data, opts);
    }
    else {
      console.log('Error: Client (' + i + ') not connected.');
    }
  }
};

// HTTP server to accept incoming MPEG1 stream
http.createServer(function (req, res) {
  console.log(
    'Stream Connected: ' + req.socket.remoteAddress +
    ':' + req.socket.remotePort + ' size: ' + width + 'x' + height
  );

  req.on('data', function (data) {
    wsServer.broadcast(data, { binary: true });
  });
}).listen(configServer.streamPort, function () {
  console.log('Listening for video stream on port ' + configServer.streamPort);

  // Run do_ffmpeg.sh from node
  childProcess.exec('../../bin/do_ffmpeg.sh');
});

// Second WebSocket server on port 8086
var wsServer2 = new (ws.Server)({ port: 8086 });
wsServer2.on('connection', function(socket) {
  console.log('New WebSocket Connection on 2nd WebSocket server (' + wsServer2.clients.length + ' total)');

  socket.on('message', function(message) {
    console.log('received: %s', message);
  });

  socket.on('close', function(code, message) {
    console.log('Disconnected WebSocket on 2nd WebSocket server (' + wsServer2.clients.length + ' total)');
  });
});

module.exports.app = app;
```

`index.html`:

```
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="initial-scale=1"/>
  <title>edi-cam</title>
  <style type="text/css">
    .container {
      margin-top: 10%;
      text-align: center;
    }

    #canvas-video {
      width: 640px;
      height: 480px;
      border: 1px solid #ccc;
    }
  </style>
</head>
<body>
  <!-- Reference: https://github.com/phoboslab/jsmpeg/blob/master/stream-example.html -->

  <div class="container">
    <!--
      The canvas size specified here is the "initial" internal resolution. jsmpeg will
      change this internal resolution to whatever the source provides. The size the
      canvas is displayed on the website is dictated by the CSS style.
    -->
    <canvas id="canvas-video" width="640" height="480"></canvas>

    <input type="button" value="Button" onclick="sendMsg()">
  </div>

  <script src="/jsmpg.js"></script>
  <script type="text/javascript">
    // CHANGE THIS TO THE APPROPRIATE WS ADDRESS
    var wsUrl = 'ws://eejun-edison02.local:8084/';

    // Show loading notice
    var canvas = document.getElementById('canvas-video');
    var ctx = canvas.getContext('2d');
    ctx.fillStyle = '#333';
    ctx.fillText('Loading...', canvas.width/2-30, canvas.height/3);

    // Start the player
    var client = new WebSocket(wsUrl);
    var player = new jsmpeg(client, { canvas:canvas });

    // Second WebSocket client
    var client2 = new WebSocket('ws://eejun-edison02.local:8086');
    client2.onopen = function (event) {
      client2.send("Hello, server!");
    };

    function sendMsg() {
      var msg = "Button clicked!";
      console.log(msg);
      client2.send(msg);
    }
  </script>
</body>
</html>
```

This is what I get on the server console after clicking the Button on the browser page:

```
root@eejun-edison02:~/edi-cam/web/server# node server.js 
WebSocket server listening on port 8084
HTTP server listening on port 8080
Listening for video stream on port 8082
Stream Connected: 127.0.0.1:37856 size: 320x240
New WebSocket Connection (1 total)
New WebSocket Connection on 2nd WebSocket server (1 total)
received: Hello, server!
GET /favicon.ico 200 35.843 ms - 1681
received: Button clicked!
```

Hope this helps!

**Comment by digerati73** [comment]
thanks alot, as if by magic, it works, i received a message.
something odd is difference  between code of yours and mine  is position of added code.
i think i will fail again but,
it works .

Maybe you have a magical power ... ha ha ha...

problem remained is segmentation fault 

and  i can't call a function that is defined in scripts when i push the button in web browser page

serious problem is segmentation fault...

i think after begin of program , about 2~3 minute , program die.

no more working..

so, i can't use..

but, if i use only one websocket , i think there is no problem program die.

push button message call script function is related with html5 function.

i need more study about html5 and javascript

so, segmentation fault is very critical....if i can't fix this problem 
i think i can't use 2nd websocket.

thank you 

i need to study more about websocket that is used this program

would you suggest some book or internet site ? 

i buy so many books, but there is mostly about  socket.io ,
moreover i read a book "the definition guide to html5 websocket written by vanessa wang"
but it didn't helps me as i expect,..

i will buy another book "getting started with html5 websocket programming"...

^^

**Comment by digerati73** [comment]
oh! i find something new,
i use chrome debug view as debugger,

i change the some code of index.html,
and then i run the server code
and then after i connect server with web browser,
i open the source code of index.html at chrome webbrowser,
there is surprising happening.
the index,html code is not changed....

oh my god..

after stop the program , i check if i didn't change the code of index.html
but , it is changed. so i think
web browser's cache is working so, new updated page is not received....

what do you think about this happening...????

**Comment by digerati73** [comment]
i solve a problem sending button message

   function sendMsg(e) {
   client2.send("drejkim is very kind ");
   console.log("sendMsg worked");
   }

..........................

<input id="bn_id" type="button" value="SHOOT" onclick="sendMsg(event)"


this is first gift for you ^^;;;;;;;;

there is only one thing left to solve...

oh, i read again your mention, you already did it ...^^;;;;;;;;;;;;;;;

segmentation fault.....

**Comment by digerati73** [comment]
![success](https://cloud.githubusercontent.com/assets/7827525/6393267/f1d603ac-be0b-11e4-9744-a4ad71a9b975.png)

i find this article...

http://www.quora.com/What-are-the-ways-to-fix-segmentation-fault-in-linux-for-OpenCV-program-in-C

http://ubuntuforums.org/showthread.php?t=2071988

segmentation fault is problem of memory allocation and clear of not permitted...

what make this problem by making 2nd websocket 

i think somewhere 2nd websocket  invade 1st websocket memory... where is there ?? in code??

**Comment by estherjk** [comment]
@digerati73 it should also work with just one WebSocket server, and it's a pretty straightforward modification. This time, I'll just include the sections of the code I modified.

`server.js`:

```
// WebSocket server
var wsServer = new (ws.Server)({ port: configServer.wsPort });
console.log('WebSocket server listening on port ' + configServer.wsPort);

wsServer.on('connection', function(socket) {
  // Send magic bytes and video size to the newly connected socket
  // struct { char magic[4]; unsigned short width, height;}
  var streamHeader = new Buffer(8);

  streamHeader.write(STREAM_MAGIC_BYTES);
  streamHeader.writeUInt16BE(width, 4);
  streamHeader.writeUInt16BE(height, 6);
  socket.send(streamHeader, { binary: true });

  console.log('New WebSocket Connection (' + wsServer.clients.length + ' total)');

  socket.on('message', function(message) {
    console.log('received: %s', message);
  });

  socket.on('close', function(code, message){
    console.log('Disconnected WebSocket (' + wsServer.clients.length + ' total)');
  });
});
```

`index.html`:

```
<body>
  <!-- Reference: https://github.com/phoboslab/jsmpeg/blob/master/stream-example.html -->

  <div class="container">
    <!--
      The canvas size specified here is the "initial" internal resolution. jsmpeg will
      change this internal resolution to whatever the source provides. The size the
      canvas is displayed on the website is dictated by the CSS style.
    -->
    <canvas id="canvas-video" width="640" height="480"></canvas>

    <input type="button" value="Button" onclick="sendMsg()">
  </div>

  <script src="/jsmpg.js"></script>
  <script type="text/javascript">
    // CHANGE THIS TO THE APPROPRIATE WS ADDRESS
    var wsUrl = 'ws://eejun-edison02.local:8084/';

    // Show loading notice
    var canvas = document.getElementById('canvas-video');
    var ctx = canvas.getContext('2d');
    ctx.fillStyle = '#333';
    ctx.fillText('Loading...', canvas.width/2-30, canvas.height/3);

    // Start the player
    var client = new WebSocket(wsUrl);
    var player = new jsmpeg(client, { canvas:canvas });

    function sendMsg() {
      var msg = "Button clicked!";
      console.log(msg);
      client.send(msg);
    }
  </script>
</body>
```

Hope this resolves your issues. Just FYI, I haven't had a `Segmentation fault` error yet... so not sure if I can replicate....

**Comment by digerati73** [comment]
^^;

i fix the code like above, problem happens too

i need a debugging..

how can i easily debug code in edison ?

is it possible to debug this server.js by webstorm

client code, index.html is debugged by web browser.

but how can i debug server.js in runtime? 
there is only "console.log"..... ^^;;

my os of pc is windows 8.1 pro 64bit,  ....

now, there is no segmentation error.... 

^^ ????   state is unstable?

**Comment by digerati73** [comment]
i find node-inspector  , it can be used to debug node.js code at chrome ,

is it possible too at edison ??  if so, how can i debug edison at chrome browser, 

at first  node --debug server.js

and then run one more terminal . = > how can i? there is only one serial port in edison....

and then run node-inspector...

**Comment by estherjk** [comment]
You can SSH into Edison if you would like another terminal window. To SSH, I believe you must have set a password when you configured Edison. If you haven't created a password, type `configure_edsion --pasword` and follow the on-screen instructions. Then you can SSH by typing `ssh root@<IP address of Edison>` or `ssh root@edison.local`, where `edison` is the name of your Edison.

**Comment by digerati73** [comment]
thanks angel..

**Comment by digerati73** [comment]
i think, segmentation fault happens randomly, 
i want to use node-inspector to debug, 
but node-inspector is not for x86 linux, if i want to use it 
i am suggested in two way, both of them is not easy for me

one of them is use node-gyp,,, oh it is difficult....

**Comment by digerati73** [comment]
i doubt the SDHC card...
i check the state of SD 
and,  there is several troubles...

like this...

![opkg update bug](https://cloud.githubusercontent.com/assets/7827525/6430997/20e779cc-c065-11e4-8cb6-f08e4a0788bf.png)

so i decide to Re install... all of SD card again, again

at third time, 

i install intel's repositories....

and now...

![final no error edi-cam-tank](https://cloud.githubusercontent.com/assets/7827525/6430953/e8b055f2-c063-11e4-9762-1478704aa60a.png)

now,....

so fa so good

after reinstall all of sdhc card...

there is no segmentation fault...

but, as above picture 
there is not enough memory for root
root has ffmpeg directory... 
size of used is 97 %.... 

can i move ffmpeg to the other directory ? 
or how can i increase the size of root directory? 

if i install something , there happens trouble, truncated, not enough memory ....so

so other module installation failed.

so far so go~~~ood...^^

**Comment by estherjk** [comment]
@digerati73 if you download the latest Edison image from Intel's site, it now has 1.4 GB for the root directory. You can also take a look at this [blog post](http://drejkim.com/blog/2014/11/22/building-an-edison-image-and-changing-the-root-partition-size/) I wrote if you want to try building your own image.

**Comment by digerati73** [comment]
i read your blog post, is there any way to making new image not at linux but at windows 8.1 pro ?

**Comment by estherjk** [comment]
@digerati73 Unfortunately, you need Linux to build a new image. But again, if you only need to increase the space on root, the latest Edison image that can be downloaded from Intel's site has 1.4 GB, which should be plenty for you. Please try that first.

**Comment by digerati73** [comment]
i tried to do you said, but there is no change in size of root...

i used the latest edison image(http://downloadmirror.intel.com/24698/eng/edison-image-ww05-15.zip)
but , the size of root is not 1.4GB

how can i do this?

**Comment by digerati73** [comment]
can i use this project at intel Galileo gen 2 ?

**Comment by estherjk** [comment]
See #2 about issues with running edi-cam on Galileo. It may not have enough power.

As for using the latest Edison image... what's the size of root when you type `df -h`?

**Comment by estherjk** [comment]
It turns out the ww05 image does set the root partition to 1.4GB, but only if you run `flashall.sh`. You can run the flashall script in Linux. I believe you can also use the flashall.bat script for Windows. Unfortunately, it does not do this automatically if you just follow the Getting Started guide. Intel is aware of the issue. Hopefully this will help you increase the root partition size.
