### ISSUE TITLE
npm packages

### ISSUE THREAD

**Issue by bhuvanchandradv** [drejkim/edi-cam#4]
Hello drejkim,

I was not having much knowledge in using the npm/java.
As i was following the instructions on readme file, while doing npm install, i was getting few errors and i was not successful in installing the dependencies.
log(npm install):
root@edison:~/edi-cam/web/server# npm install
npm WARN package.json http@0.0.0 http is also the name of a node core module.
npm WARN package.json http@0.0.0 No description
npm WARN package.json http@0.0.0 No repository field.
npm WARN package.json node.js@0.0.0 No repository field.
npm http GET https://registry.npmjs.org/ws
npm http GET https://registry.npmjs.org/express
npm http 304 https://registry.npmjs.org/ws
npm http 304 https://registry.npmjs.org/express
npm ERR! Failed to parse json
npm ERR! Unexpected end of input
npm ERR! File: /home/root/.npm/express/4.10.1/package/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! System Linux 3.10.17-poky-edison+
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /home/root/edi-cam/web/server
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! file /home/root/.npm/express/4.10.1/package/package.json
npm ERR! code EJSONPARSE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/root/edi-cam/web/server/npm-debug.log
npm ERR! not ok code 0

log(node server.js):
root@edison:~/edi-cam/web/server# node server.js 

module.js:117
    throw e;
          ^
SyntaxError: Error parsing /home/root/edi-cam/web/server/node_modules/express/package.json: Unexpected end of input
    at Object.parse (native)
    at readPackage (module.js:113:52)
    at tryPackage (module.js:123:13)
    at Function.Module._findPath (module.js:190:18)
    at Function.Module._resolveFilename (module.js:336:25)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/root/edi-cam/web/server/server.js:3:15)
    at Module._compile (module.js:456:26)

Is there any thing I'm missing ? can you please help me with this problem.
## 

Bhuvan

**Comment by estherjk** [comment]
Can you run `npm cache clean` and remove `node_modules` before running `npm install` again? Do you see still run into the same issues?

**Comment by bhuvanchandradv** [comment]
After following those steps, it worked fine. installed modules without any errors, thanks :-)

**Comment by estherjk** [comment]
Excellent! I'll go ahead and close this.

**Comment by kcyeong92** [comment]
After running npm cache clean and remove node_modules, 


root@fyp_ykc:/edi-cam/web/server# rm -R node_modules/
root@fyp_ykc:/edi-cam/web/server# npm cache clean
root@fyp_ykc:/edi-cam/web/server# npm install
npm http GET https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/morgan
npm http GET https://registry.npmjs.org/ws
npm http 200 https://registry.npmjs.org/morgan
npm http GET https://registry.npmjs.org/morgan/-/morgan-1.4.1.tgz
npm http 200 https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/express/-/express-4.10.1.tgz
npm http 200 https://registry.npmjs.org/ws
npm http GET https://registry.npmjs.org/ws/-/ws-0.4.32.tgz
npm http 200 https://registry.npmjs.org/express/-/express-4.10.1.tgz
npm http 200 https://registry.npmjs.org/morgan/-/morgan-1.4.1.tgz
npm http 200 https://registry.npmjs.org/ws/-/ws-0.4.32.tgz
npm ERR! Error: ENOSPC, write
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.10.17-poky-edison+
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /edi-cam/web/server
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ENOSPC
npm ERR! errno 54
npm ERR! Error: ENOSPC, write
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.10.17-poky-edison+
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /edi-cam/web/server
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ENOSPC
npm ERR! errno 54
npm ERR! Error: ENOSPC, write
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.10.17-poky-edison+
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /edi-cam/web/server
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ENOSPC
npm ERR! errno 54
npm ERR! Error: ENOSPC, write
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.10.17-poky-edison+
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /edi-cam/web/server
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ENOSPC
npm ERR! errno 54
npm ERR! Error: ENOSPC, write
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.10.17-poky-edison+
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /edi-cam/web/server
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ENOSPC
npm ERR! errno 54
npm ERR! Error: ENOSPC, write
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.10.17-poky-edison+
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /edi-cam/web/server
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ENOSPC
npm ERR! errno 54
npm ERR! Error: ENOSPC, write
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.10.17-poky-edison+
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /edi-cam/web/server
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ENOSPC
npm ERR! errno 54
npm ERR! Error: ENOSPC, mkdir '/edi-cam/web/server/node_modules/ws/src'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.10.17-poky-edison+
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /edi-cam/web/server
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! path /edi-cam/web/server/node_modules/ws/src
npm ERR! fstream_path /edi-cam/web/server/node_modules/ws/src/bufferutil.cc
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOSPC
npm ERR! errno 54
npm ERR! fstream_stack /usr/lib/node_modules/npm/node_modules/fstream/lib/writer.js:171:23
npm ERR! fstream_stack /usr/lib/node_modules/npm/node_modules/mkdirp/index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOSPC, write
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.10.17-poky-edison+
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /edi-cam/web/server
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ENOSPC
npm ERR! errno 54
npm ERR! Error: ENOSPC, write
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.10.17-poky-edison+
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /edi-cam/web/server
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ENOSPC
npm ERR! errno 54
npm ERR! Error: ENOSPC, write
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.10.17-poky-edison+
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /edi-cam/web/server
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ENOSPC
npm ERR! errno 54
npm ERR! Error: ENOSPC, mkdir '/edi-cam/web/server/node_modules/express/lib'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
npm ERR! System Linux 3.10.17-poky-edison+
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /edi-cam/web/server
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! path /edi-cam/web/server/node_modules/express/lib
npm ERR! fstream_path /edi-cam/web/server/node_modules/express/lib/application.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOSPC
npm ERR! errno 54
npm ERR! fstream_stack /usr/lib/node_modules/npm/node_modules/fstream/lib/writer.js:171:23
npm ERR! fstream_stack /usr/lib/node_modules/npm/node_modules/mkdirp/index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOSPC, write
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.10.17-poky-edison+
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /edi-cam/web/server
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ENOSPC
npm ERR! errno 54
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /edi-cam/web/server/npm-debug.log
npm ERR! not ok code 0
