### ISSUE TITLE
Adding facial recognition

### ISSUE THREAD

**Issue by xiochanik** [drejkim/edi-cam#5]
Hi,

I want to add facial recognition to your project, can you guide me to where within the code can I take the frame coming from the stream do the recognition and then display it in the http server?

Thanks

**Comment by estherjk** [comment]
I recommend taking a look at https://github.com/drejkim/face-detection-node-opencv, which is a separate demo I've created that uses the Node.js bindings for OpenCV. Unfortunately, performance is poor and I can only manage ~1 fps when running on Edison.

However, this person was able to use normal OpenCV and a mjpeg streamer, and the results look pretty good: https://www.youtube.com/watch?v=LYWtUst0N_o.
