### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by oooseun** [drejkim/edi-cam#7]
Hi, i'm trying to implement screenshots on motion detection using ffmpeg. 
I tried several solutions but i'm running into a stumbling block with the right video source. i can't use '/dev/video0' because 'resource is in use (by edi-cam)' and a direct http output isn't working (using http://127.0.0.1:8082). Any ideas ?

Also as this isn't really an "issue" i tried to avoid starting one up, but couldn't find a reliable way to contact you. Thanks

**Comment by estherjk** [comment]
Unfortunately, I don't have any experience doing this with ffmpeg. However, I have used the [motion](http://www.lavrsen.dk/foswiki/bin/view/Motion) package before on a Raspberry Pi to see the live video stream, as well as save images / video when motion is detected. Take a look at this [project](https://communities.intel.com/docs/DOC-23972) that uses motion on Intel Edison. Hope this still at least addresses your question! Wish I could help more directly with ffmpeg.

**Comment by oooseun** [comment]
Hi. So i did take a look at that project (although i had seen it before, i actually was able to grasp everything that was going on this time). I found motion to be the solution to my problem! which makes me wonder why this wasn't the first approach for 'edi'cam'? They both have their pro's and cons namely edi-cam/ffmpeg is faster(lag-wise) but slower when the resolution is ramped up. edi-cam's output format is hard to work with & i had trouble getting it to port forward correctly. motion does use 2x the cpu (IMExperience) and has a much worse image quality. Sorry for going on about their differences, and THANKS! a lot for doing this and making this open source!

**Comment by estherjk** [comment]
The image quality and video rate of motion are precisely the reasons why I wanted to try out ffmpeg. As you pointed out, they have their pros and cons, but I really wanted a solution that could stream video at a faster rate. I also wanted to create a Node.js example to illustrate how it can be used on Edison. In any case, glad motion has worked out for you!
